import classical_groups_algebro_geometric_aspects_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace classical_groups_algebro_geometric_aspects_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end classical_groups_algebro_geometric_aspects_theorem_canonical_lane_mathlib
end HautevilleHouse
